#
# Makefile for libzlst
#

ifneq ($(wildcard ../config.mak),)
include ../config.mak
endif

VMAJOR = 1
VMINOR = 0
VRELEA = 0

obj-y := zlst.o

NAME = zlst
TYPE = lib
DESC = common bidirection list
HEADERS = zlst.h

include ../common.mak
