#
# Makefile for libzlst
#

include ../config.mak

VMAJOR = 1
VMINOR = 0
VMICRO = 0

obj-y := tobin.o

NAME = tobin
TYPE = exe

CFLAGS += -I../libzutil

LDFLAGS += -L../libzutil -lzutil

include ../common.mak
