NAME = param_xml
SRCS = param_xml.c
HEADERS = param_xml.h

CFLAGS = -I/usr/include/libxml2

LDFLAGS  = -L../libzlst -lzlst
LDFLAGS += -L/lib -lxml2

VMAJOR = 1
VMINOR = 1
VMICRO = 0

include ../common.mak
