DIRS = libts libnet catts catip tsana tots

# Do not print "Entering directory ..."
MAKEFLAGS += --no-print-directory

define make_dirs
	@for dir in $(DIRS); do echo; echo "---> $$dir:"; $(MAKE) -C $$dir -f Makefile.linux $@; done
endef

all doc clean explain depend install uninstall release:
	$(make_dirs)
