all release install uninstall clean:
	@cd libts
	@echo "---> libts:"
	-@$(MAKE) /NOLOGO /F Makefile.msvc $@
	@cd ..\catts
	@echo "---> catts:"
	-@$(MAKE) /NOLOGO /F Makefile.msvc $@
	@cd ..\catip
	@echo "---> catip:"
	-@$(MAKE) /NOLOGO /F Makefile.msvc $@
	@cd ..\tsana
	@echo "---> tsana:"
	-@$(MAKE) /NOLOGO /F Makefile.msvc $@
	@cd ..\tots
	@echo "---> tots:"
	-@$(MAKE) /NOLOGO /F Makefile.msvc $@
#	@cd ..\toip
#	@echo "---> toip:"
#	-@$(MAKE) /NOLOGO /F Makefile.msvc $@
	@cd ..
